export const SUPABASE_URL = "https://egmaiupxovkmvhvhmrax.supabase.co";

export const SUPABASE_ANON_KEY =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnbWFpdXB4b3ZrbXZodmhtcmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0NTE0NzAsImV4cCI6MjA4NzAyNzQ3MH0.iQtQ63OI6HvRdMl5PtdQPVw3_kS1rKh8kHuRwHsCt3A";
