-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: empleado
-- Comentario: Tabla de empleados para el sistema SIA de Premium Consultores
CREATE TABLE IF NOT EXISTS empleado (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    cedula NUMERIC NOT NULL,
    nombre TEXT NOT NULL,
    cargo TEXT,
    contratado BOOLEAN DEFAULT FALSE,
    tlf NUMERIC,
    fecha_ingreso TIMESTAMPTZ DEFAULT NOW(),
    departamento TEXT
);

COMMENT ON TABLE empleado IS 'Tabla de empleados para el sistema SIA de Premium Consultores';

-- Table: competencias
-- Comentario: Tabla de competencias para el sistema SIA de Premium Consultores
CREATE TABLE IF NOT EXISTS competencias (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT
);

COMMENT ON TABLE competencias IS 'Tabla de competencias para el sistema SIA de Premium Consultores';

-- Table: perfil_meta
-- Comentario: Tabla de perfil meta para el sistema SIA de Premium Consultores
CREATE TABLE IF NOT EXISTS perfil_meta (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_obj TEXT NOT NULL,
    competencia_id INT8 REFERENCES competencias(id) ON DELETE CASCADE,
    puntaje_ideal NUMERIC NOT NULL
);

COMMENT ON TABLE perfil_meta IS 'Tabla de perfil meta para el sistema SIA de Premium Consultores';

-- Table: evaluacion360
-- Comentario: Tabla de evaluación 360 para el sistema SIA de Premium Consultores
CREATE TABLE IF NOT EXISTS evaluacion360 (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    evaluado_id UUID REFERENCES empleado(id) ON DELETE CASCADE,
    competencia_id INT8 REFERENCES competencias(id) ON DELETE CASCADE,
    puntaje INT2 CHECK (puntaje >= 1 AND puntaje <= 5),
    tipo_evaluador TEXT,
    comentario TEXT
);

COMMENT ON TABLE evaluacion360 IS 'Tabla de evaluación 360 para el sistema SIA de Premium Consultores';
