-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: empleado
-- Comentario: Tabla de empleados para el sistema SIA de Premium Consultores
CREATE TABLE IF NOT EXISTS empleado (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    cedula NUMERIC NOT NULL,
    nombre TEXT NOT NULL,
    cargo TEXT,
    contratado BOOLEAN DEFAULT FALSE,
    tlf NUMERIC,
    fecha_ingreso TIMESTAMPTZ DEFAULT NOW(),
    departamento TEXT
);

COMMENT ON TABLE empleado IS 'Tabla de empleados para el sistema SIA de Premium Consultores';

-- Table: competencias
-- Comentario: Tabla de competencias para el sistema SIA de Premium Consultores
CREATE TABLE IF NOT EXISTS competencias (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT
);

COMMENT ON TABLE competencias IS 'Tabla de competencias para el sistema SIA de Premium Consultores';

-- Table: perfil_meta
-- Comentario: Tabla de perfil meta para el sistema SIA de Premium Consultores
CREATE TABLE IF NOT EXISTS perfil_meta (
    id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_obj TEXT NOT NULL,
    competencia_id INT8 REFERENCES competencias(id) ON DELETE CASCADE,
    puntaje_ideal NUMERIC NOT NULL
);

COMMENT ON TABLE perfil_meta IS 'Tabla de perfil meta para el sistema SIA de Premium Consultores';

-- Table: evaluacion360
-- Comentario: Tabla de evaluación 360 para el sistema SIA de Premium Consultores
CREATE TABLE IF NOT EXISTS evaluacion360 (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    evaluado_id UUID REFERENCES empleado(id) ON DELETE CASCADE,
    competencia_id INT8 REFERENCES competencias(id) ON DELETE CASCADE,
    puntaje INT2 CHECK (puntaje >= 1 AND puntaje <= 5),
    tipo_evaluador TEXT,
    comentario TEXT
);

COMMENT ON TABLE evaluacion360 IS 'Tabla de evaluación 360 para el sistema SIA de Premium Consultores';

-- Crear tabla de candidatos
CREATE TABLE IF NOT EXISTS candidatos (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    cedula TEXT UNIQUE NOT NULL,
    nombre TEXT NOT NULL,
    telefono TEXT,
    cv_url TEXT,
    departamento_deseado TEXT DEFAULT 'Finanzas',
    años_experiencia INT2 DEFAULT 0,
    formacion TEXT CHECK (formacion IN ('Secundaria', 'Técnico', 'Universitaria', 'PostGrado', 'Doctorado')),
    respuestas_evaluacion JSONB,
    fecha_registro TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE candidatos IS 'Tabla para el módulo de reclutamiento de Premium Consultores';

-- Insertar un candidato de prueba con la estructura JSONB correcta
INSERT INTO candidatos (cedula, nombre, telefono, departamento_deseado, años_experiencia, formacion, respuestas_evaluacion)
VALUES (
    'V-28123456', 
    'María González', 
    '0414-1234567', 
    'Finanzas', 
    5, 
    'Universitaria',
    '{
        "contaduria_1": {
            "texto": "Tengo experiencia analizando balances generales.",
            "puntaje": 8
        },
        "agilidad_1": {
            "texto": "Priorizo tareas según su impacto financiero.",
            "puntaje": 10
        },
        "aporte_valor": {
            "texto": "Puedo automatizar los reportes financieros usando macros y Python.",
            "puntaje": null
        }
    }'::jsonb
);